export const boxCompoundedVariants = [
  {
    size: "xs",
    content: "xs",
    container: true,
    class: "rounded-xs+xs",
  },
  {
    size: "xs",
    content: "xs",
    container: false,
    class: "rounded-xs",
  },
  {
    size: "xs",
    content: "sm",
    container: true,
    class: "rounded-xs+sm",
  },
  {
    size: "xs",
    content: "sm",
    container: false,
    class: "rounded-xs",
  },
  {
    size: "xs",
    content: "md",
    container: true,
    class: "rounded-xs+md",
  },
  {
    size: "xs",
    content: "md",
    container: false,
    class: "rounded-xs",
  },
  {
    size: "xs",
    content: "lg",
    container: true,
    class: "rounded-xs+lg",
  },
  {
    size: "xs",
    content: "lg",
    container: false,
    class: "rounded-xs",
  },
  {
    size: "xs",
    content: "xl",
    container: true,
    class: "rounded-xs+xl",
  },
  {
    size: "xs",
    content: "xl",
    container: false,
    class: "rounded-xs",
  },
  {
    size: "sm",
    content: "xs",
    container: true,
    class: "rounded-sm+xs",
  },
  {
    size: "sm",
    content: "xs",
    container: false,
    class: "rounded-sm",
  },
  {
    size: "sm",
    content: "sm",
    container: true,
    class: "rounded-sm+sm",
  },
  {
    size: "sm",
    content: "sm",
    container: false,
    class: "rounded-sm",
  },
  {
    size: "sm",
    content: "md",
    container: true,
    class: "rounded-sm+md",
  },
  {
    size: "sm",
    content: "md",
    container: false,
    class: "rounded-sm",
  },
  {
    size: "sm",
    content: "lg",
    container: true,
    class: "rounded-sm+lg",
  },
  {
    size: "sm",
    content: "lg",
    container: false,
    class: "rounded-sm",
  },
  {
    size: "sm",
    content: "xl",
    container: true,
    class: "rounded-sm+xl",
  },
  {
    size: "sm",
    content: "xl",
    container: false,
    class: "rounded-sm",
  },
  {
    size: "md",
    content: "xs",
    container: true,
    class: "rounded-md+xs",
  },
  {
    size: "md",
    content: "xs",
    container: false,
    class: "rounded-md",
  },
  {
    size: "md",
    content: "sm",
    container: true,
    class: "rounded-md+sm",
  },
  {
    size: "md",
    content: "sm",
    container: false,
    class: "rounded-md",
  },
  {
    size: "md",
    content: "md",
    container: true,
    class: "rounded-md+md",
  },
  {
    size: "md",
    content: "md",
    container: false,
    class: "rounded-md",
  },
  {
    size: "md",
    content: "lg",
    container: true,
    class: "rounded-md+lg",
  },
  {
    size: "md",
    content: "lg",
    container: false,
    class: "rounded-md",
  },
  {
    size: "md",
    content: "xl",
    container: true,
    class: "rounded-md+xl",
  },
  {
    size: "md",
    content: "xl",
    container: false,
    class: "rounded-md",
  },
  {
    size: "lg",
    content: "xs",
    container: true,
    class: "rounded-lg+xs",
  },
  {
    size: "lg",
    content: "xs",
    container: false,
    class: "rounded-lg",
  },
  {
    size: "lg",
    content: "sm",
    container: true,
    class: "rounded-lg+sm",
  },
  {
    size: "lg",
    content: "sm",
    container: false,
    class: "rounded-lg",
  },
  {
    size: "lg",
    content: "md",
    container: true,
    class: "rounded-lg+md",
  },
  {
    size: "lg",
    content: "md",
    container: false,
    class: "rounded-lg",
  },
  {
    size: "lg",
    content: "lg",
    container: true,
    class: "rounded-lg+lg",
  },
  {
    size: "lg",
    content: "lg",
    container: false,
    class: "rounded-lg",
  },
  {
    size: "lg",
    content: "xl",
    container: true,
    class: "rounded-lg+xl",
  },
  {
    size: "lg",
    content: "xl",
    container: false,
    class: "rounded-lg",
  },
  {
    size: "xl",
    content: "xs",
    container: true,
    class: "rounded-xl+xs",
  },
  {
    size: "xl",
    content: "xs",
    container: false,
    class: "rounded-xl",
  },
  {
    size: "xl",
    content: "sm",
    container: true,
    class: "rounded-xl+sm",
  },
  {
    size: "xl",
    content: "sm",
    container: false,
    class: "rounded-xl",
  },
  {
    size: "xl",
    content: "md",
    container: true,
    class: "rounded-xl+md",
  },
  {
    size: "xl",
    content: "md",
    container: false,
    class: "rounded-xl",
  },
  {
    size: "xl",
    content: "lg",
    container: true,
    class: "rounded-xl+lg",
  },
  {
    size: "xl",
    content: "lg",
    container: false,
    class: "rounded-xl",
  },
  {
    size: "xl",
    content: "xl",
    container: true,
    class: "rounded-xl+xl",
  },
  {
    size: "xl",
    content: "xl",
    container: false,
    class: "rounded-xl",
  },
];
