name: Trigger production deployment

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

defaults:
  run:
    shell: bash

jobs:
  tag-image:
    runs-on: ubuntu-latest
    env:
      IMAGE_URL: europe-west1-docker.pkg.dev/angle-artifacts/angle-docker-registry/merkl-app
    steps:
      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCLOUD_SECRET_ARTIFACTS }}'
      - name: Login to Docker
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev
      - name: Pull and tag image
        run: |
          export SHORT_SHA=${GITHUB_SHA:0:7}
          export VERSION=${GITHUB_REF#refs/tags/}
          docker pull $IMAGE_URL:$SHORT_SHA
          docker tag $IMAGE_URL:$SHORT_SHA $IMAGE_URL:$VERSION
          docker push $IMAGE_URL:$VERSION
  trigger-production-deployment:
    runs-on: ubuntu-latest
    needs: tag-image
    steps:
      - name: Install dependencies
        run: |
          sudo snap install yq
      - name: Clone deployments repo
        uses: actions/checkout@v3
        with:
          repository: AngleProtocol/deployments
          token: ${{ secrets.ACCESS_TOKEN }}
          path: deployments
      - name: Modify config.production.yaml and push to deployments
        run: |
          cd deployments

          export VERSION=${GITHUB_REF#refs/tags/}
          yq -i '.merkl-app.version = strenv(VERSION)' ./config.production.yaml

          git config --global user.email "baptiste@angle.money"
          git config --global user.name "BaptistG"

          git add ./config.production.yaml
          git commit -m "Update config.production.yaml with merkl-app version $VERSION"

          git push
